# 翻译接口选择
# google / aliyun / baidu / youdao
provider: google

# 代理地址
# 这会影响整个服务器，请谨慎使用
proxy:
  enable: false #是否启用代理
  host: "127.0.0.1"
  port: 1080

# 阿里云翻译账号配置 不使用阿里云接口请忽略
# https://usercenter.console.aliyun.com/#/manage/ak
aliyun:
  accessKeyId: "1234"
  accessKeySecret: "1234"

# 百度翻译账号配置 不使用百度翻译接口请忽略
# https://fanyi-api.baidu.com/
baidu:
  appId: "1234"
  secretKey: "1234"